#!/usr/bin/env python3
"""Write the Xcode shell's link settings from CMake's p2_ios_link_check link line.

The Xcode project (ios/Pikmin2.xcodeproj) compiles only main.m; everything else
is the static archives and frameworks CMake already links into
p2_ios_link_check. Reading that link line keeps the two links identical.
"""
import argparse
import shlex
from pathlib import Path

parser = argparse.ArgumentParser()
parser.add_argument('--link-txt', type=Path, required=True)
parser.add_argument('--build-dir', type=Path, required=True)
parser.add_argument('--out', type=Path, required=True)
args = parser.parse_args()

words = shlex.split(args.link_txt.read_text())
flags = []
i = 1  # words[0] is the compiler driver
while i < len(words):
    word = words[i]
    if word == '-o':
        i += 2
        continue
    if word in ('-framework', '-weak_framework', '-Xlinker'):
        flags += [word, words[i + 1]]
        i += 2
        continue
    if word.endswith('.tbd'):  # SDK system library, e.g. .../usr/lib/libbz2.tbd
        flags.append('-l' + Path(word).stem.removeprefix('lib'))
    elif word.endswith('.dylib'):
        raise SystemExit(f'ios_link_config: {word} is a dynamic library; iOS builds must be static')
    elif word.endswith('.a'):
        path = Path(word)
        flags.append(str(path if path.is_absolute() else (args.build_dir / path).resolve()))
    elif word.startswith('-l') or word.startswith('-Wl,-framework') or word.startswith('-Wl,-weak_framework'):
        flags.append(word)
    i += 1
# CMake links with the C++ driver, which adds libc++ itself; Xcode links main.m as C.
flags.append('-lc++')
if not any(f.endswith('.a') for f in flags):
    raise SystemExit(f'ios_link_config: no archives found in {args.link_txt}')
args.out.write_text('// Generated by tools/ios_link_config.py from p2_ios_link_check; do not edit.\n'
                    'P2_LINK_FLAGS = ' + ' '.join(shlex.quote(f) for f in flags) + '\n')
print(f'ios_link_config: {sum(f.endswith(".a") for f in flags)} archives -> {args.out}')
